/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArrowControl: typeof import('./src/components/ArrowControl.vue')['default']
    ArrowSymbol: typeof import('./src/components/ArrowSymbol.vue')['default']
    GamePlay: typeof import('./src/components/GamePlay.vue')['default']
    HighScore: typeof import('./src/pages/high-score.vue')['default']
    Pages: typeof import('./src/pages/index.vue')['default']
    Play: typeof import('./src/pages/play/index.vue')['default']
    'Round-[id]': typeof import('./src/pages/play/round-[id].vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignIn: typeof import('./src/pages/sign-in.vue')['default']
    TheAuthenticator: typeof import('./src/components/TheAuthenticator.vue')['default']
    TheScoreboard: typeof import('./src/components/TheScoreboard.vue')['default']
    TheTimer: typeof import('./src/components/TheTimer.vue')['default']
  }
}
